# tie gpsdctl to gpd lifecycle, ensures adding devices survives service restarts
[Unit]
Wants=gpsd.service
After=gpsd.service
PartOf=gpsd.service

# gpsdctl@%k service gates on USBAUTO environment for adding devices
[Service]
Environment="USBAUTO=true"
