#!/bin/bash

BUILDDIR="${ROOTDIR}/build"
BUILDDIR_TMP="${BUILDDIR}/tmp"
OUTPUT_DIR="${BUILDDIR}/output/${MACHINE}"
DEPLOY_DIR="${ROOTDIR}/images"
CACHE_DIR="${BUILDDIR}/cache"

MAKE_JOBS=$(getconf _NPROCESSORS_ONLN)


SRC_DIR_UBOOT="${BUILDDIR}/u-boot"
BUILDDIR_TMP_UBOOT="${BUILDDIR_TMP}/u-boot/${MACHINE}"
OUTPUT_DIR_UBOOT="${OUTPUT_DIR}/u-boot"

SRC_DIR_TFA="${BUILDDIR}/rzg_trusted-firmware-a"
BUILDDIR_TMP_TFA="${BUILDDIR_TMP}/tfa/${MACHINE}"
OUTPUT_DIR_TFA="${OUTPUT_DIR}/tfa"

SRC_DIR_KERNEL="${BUILDDIR}/linux-stable"
BUILDDIR_TMP_KERNEL="${BUILDDIR_TMP}/kernel"
OUTPUT_DIR_KERNEL="${OUTPUT_DIR}/kernel"

SRC_DIR_CYWFMAC="${BUILDDIR}/cyw-fmac"

SRC_DIR_RSWLAN="${BUILDDIR}/rswlan"
BUILDDIR_TMP_RSWLAN="${BUILDDIR_TMP}/rswlan"
OUTPUT_DIR_RSWLAN="${OUTPUT_DIR}/rswlan"

BUILDDIR_TMP_BOOT_IMAGE="${BUILDDIR_TMP}/boot_image/${MACHINE}"
OUTPUT_DIR_BOOT_IMAGE="${OUTPUT_DIR}/boot_image"

SRC_DIR_BUILDROOT="${BUILDDIR}/buildroot"
BUILDDIR_TMP_BUILDROOT="${BUILDDIR_TMP}/buildroot"
OUTPUT_DIR_BUILDROOT="${OUTPUT_DIR}/buildroot"

BUILDDIR_TMP_DEBIAN="${BUILDDIR_TMP}/debian"
OUTPUT_DIR_DEBIAN="${OUTPUT_DIR}/debian"

BUILDDIR_TMP_IMAGE="${BUILDDIR_TMP}/image/${MACHINE}"
OUTPUT_DIR_IMAGE="${OUTPUT_DIR}/image"

OUTPUT_DIR_FLASHWRITER="${BUILDDIR}/output/flashwriter"

set_ccache() {
    local ccache_dir="${CACHE_DIR}/ccache/$1"
    mkdir -p $ccache_dir
    export CCACHE_DIR=$ccache_dir
}
